FROM {{ registry }}/bullseye:latest

RUN {{ "python3 python3-dev python3-pip python3-setuptools git lsb-release make virtualenv" | apt_install }} \
    && mkdir /wheels && pip3 install wheel

COPY run.sh /bin/run.sh

# These volumes are respectively where the wheels will be built, and where the code for the application resides
VOLUME ["/wheels", "/deploy"]

USER nobody

WORKDIR /deploy

CMD ["/bin/run.sh"]
