FROM {{ "bookworm" | image_tag }}
RUN {{ "prometheus-statsd-exporter" | apt_install }} \
   && rm -rf /usr/share/gocode/src/github.com/prometheus

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/prometheus-statsd-exporter"]
CMD ["--log.level=warn", "--statsd.mapping-config=/etc/monitoring/prometheus-statsd.conf"]
