FROM {{ "bullseye" | image_tag }}

# We make the spool directories world-writable as we might want to run rsyslog as other users in some cases.
RUN {{ "wmf-certificates rsyslog rsyslog-kafka" | apt_install }} && chown -R nobody. /var/spool/rsyslog \
    && chmod 0777 /var/spool/rsyslog

COPY rsyslog.conf /etc/rsyslog.conf

ENTRYPOINT ["/usr/sbin/rsyslogd"]

USER {{ "nobody" | uid }}

CMD ["-n", "-iNONE"]
