FROM {{ "build" | image_tag }} as build

FROM {{ seed_image }}

USER root
COPY --from=build --chown=root /go/github.com/cert-manager/cert-manager/_bin/server/cainjector /usr/bin/cainjector

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/cainjector"]
