FROM {{ "kserve-build" | image_tag }} as build

FROM {{ "bookworm" | image_tag }}

USER root
COPY --from=build --chown=root /go/github.com/kserve/kserve/cmd/manager/manager /usr/bin/manager

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/manager"]
