FROM docker-registry.wikimedia.org/knative-build:latest as build

FROM {{ seed_image }}

USER root
COPY --from=build --chown=root /go/github.com/knative/serving/cmd/autoscaler/autoscaler /usr/bin/autoscaler

USER nobody
ENTRYPOINT ["/usr/bin/autoscaler"]
