FROM {{ "knative-build" | image_tag }} as build

FROM {{ "buster" | image_tag }}

USER root
COPY --from=build --chown=root /go/github.com/knative/serving/cmd/autoscaler/autoscaler /usr/bin/autoscaler

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/autoscaler"]
