FROM {{ "knative-build" | image_tag }} as build

FROM {{ "buster" | image_tag }}

USER root
COPY --from=build --chown=root /go/github.com/knative/serving/cmd/domain-mapping/domain-mapping /usr/bin/domain-mapping

USER {{ "nobody" | uid }}

ENTRYPOINT ["/usr/bin/domain-mapping"]
