registry: docker-registry.wikimedia.org
seed_image: docker-registry.wikimedia.org/buster:latest
namespace: istio
base_images:
  - docker-registry.wikimedia.org/bullseye:latest
  - docker-registry.wikimedia.org/bookworm:latest
known_uid_mappings:
  istio: 1337
