registry: docker-registry.wikimedia.org
seed_image: docker-registry.wikimedia.org/wikimedia-buster:latest
base_images:
  - docker-registry.wikimedia.org/wikimedia-stretch:latest
  - docker-registry.wikimedia.org/bullseye:latest
