FROM docker-registry.wikimedia.org/wikimedia-jessie:latest
MAINTAINER Giuseppe Lavagetto <joe@wikimedia.org>
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install --yes python3 python3-dev python3-virtualenv \
    python3-pip virtualenv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN virtualenv --python python3 /virtualenv \
    && /virtualenv/bin/pip install --upgrade pip \
    && /virtualenv/bin/pip install wheel
