FROM {{ 'golang1.19' | image_tag }} as build

ARG VER='1.41.0'
RUN git clone https://github.com/jaegertracing/jaeger.git \
  && cd jaeger \
  && git checkout --detach "tags/v${VER}" \
  && make build-es-index-cleaner

FROM {{ "buster" | image_tag }}
COPY --from=build \
  /go/jaeger/cmd/es-index-cleaner/es-index-cleaner-linux-amd64 \
  /bin/jaeger-es-index-cleaner
RUN {{ "wmf-certificates" | apt_install }}
USER {{ "nobody" | uid }}
ENTRYPOINT ["jaeger-es-index-cleaner"]
