FROM {{ "knative-net-istio-build" | image_tag }} as build

FROM {{ "bookworm" | image_tag }}

USER root
COPY --from=build --chown=root /go/github.com/knative/net-istio/cmd/controller/controller /usr/bin/controller

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/controller"]
