FROM {{ "knative-net-istio-build" | image_tag }} as build

FROM {{ "buster" | image_tag }}

USER root
COPY --from=build --chown=root /go/github.com/knative/net-istio/cmd/webhook/webhook /usr/bin/webhook

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/webhook"]
