FROM {{ "knative-build" | image_tag }} as build

FROM {{ seed_image }}

USER root
COPY --from=build --chown=root /go/github.com/knative/net-istio/cmd/webhook/webhook /usr/bin/webhook

USER nobody
ENTRYPOINT ["/usr/bin/webhook"]
