FROM docker-registry.wikimedia.org/wikimedia-buster:latest

RUN {{ "python3 python3-dev python3-pip python3-setuptools git" | apt_install }} \
    && pip3 install --upgrade pip \
    && mkdir /wheels && pip3 install wheel

COPY run.sh /bin/run.sh

# These volumes are respectively where the wheels will be built, and where the code for the application resides
VOLUME ["/wheels", "/deploy"]

CMD ["/bin/run.sh"]
