FROM {{ "trixie" | image_tag }} AS build

# Instead of pulling the whole Kubernetes repository, we do a sparse checkout
# of the build/pause directory so we can use the Makefile to build the binary.
# Since the Makefile is designed to build using a container, we inject
# a target (build-local) using `make --eval` to build the pause binary using
# gcc instead, while still using the CFLAGS defined by the Makefile.

{% set kubernetes_version = '1.34' %}
{% set workdir = '/tmp/workdir' %}

USER root
RUN {{ "make gcc binutils libc6-dev ca-certificates git" | apt_install }}

USER {{ "nobody" | uid }}
RUN mkdir {{ workdir }}
WORKDIR {{ workdir }}
RUN git clone --depth 1 --filter=tree:0 --sparse \
    --branch release-{{ kubernetes_version }} https://github.com/kubernetes/kubernetes.git . && \
    git sparse-checkout set build/pause && \
    cd build/pause && \
    make --eval='build-local:; /usr/bin/gcc $(CFLAGS) -o {{ workdir }}/pause linux/pause.c' build-local && \
    /usr/bin/strip {{ workdir }}/pause

FROM scratch

USER root
COPY --from=build {{ workdir }}/pause /usr/bin/pause

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/pause"]
