FROM docker-registry.wikimedia.org/bullseye

USER root
ENV GOPATH /go
ENV GOCACHE $GOPATH/.cache/go-build
ENV GOENV $GOPATH/.config/go/env
ENV PATH $GOPATH/bin:/usr/lib/go-$GOLANG_VERSION/bin:$PATH

RUN {{ "golang=2:1.15~1 ca-certificates git build-essential" | apt_install }} \
    && mkdir -p "$GOPATH/src" "$GOPATH/bin" "$GOPATH/.cache" "$GOPATH/.config" \
    && chmod -R 777 "$GOPATH"

USER nobody
WORKDIR $GOPATH
