FROM {{ seed_image }}

RUN {{ "prometheus-apache-exporter" | apt_install }} \
   && rm -rf /usr/share/gocode/src/github.com/prometheus

USER nobody
ENTRYPOINT ["/usr/bin/prometheus-apache-exporter", "-log.format", "logger:stdout?json=true"]
