FROM docker-registry.wikimedia.org/kubeflow-kfserving-build:latest as build

FROM {{ seed_image }}

USER root
COPY --from=build --chown=root /go/github.com/kubeflow/kfserving/cmd/agent/agent /usr/bin/agent

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/agent"]
