FROM {{ "knative-build" | image_tag }} as build

FROM {{ seed_image }}

USER root
COPY --from=build --chown=root /go/github.com/knative/serving/cmd/activator/activator /usr/bin/activator

USER nobody

ENTRYPOINT ["/usr/bin/activator"]
