FROM {{ "knative-build" | image_tag }} as build

FROM {{ "bookworm" | image_tag }}

USER root
COPY --from=build --chown=root /go/github.com/knative/serving/cmd/activator/activator /usr/bin/activator

USER {{ "nobody" | uid }}

ENTRYPOINT ["/usr/bin/activator"]
