FROM docker-registry.wikimedia.org/knative-build:latest as build

FROM {{ seed_image }}

USER root
COPY --from=build --chown=root /go/github.com/knative/serving/cmd/queue/queue /usr/bin/queue

USER nobody
ENTRYPOINT ["/usr/bin/queue"]
