FROM {{ "bookworm" | image_tag }}
RUN {{ "prometheus-mcrouter-exporter" | apt_install }} \
   && rm -rf /usr/share/gocode/src/github.com/prometheus

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/prometheus-mcrouter-exporter"]
CMD ["--mcrouter.address", "localhost:5000", "-mcrouter.server_metrics", "-web.listen-address", ":9151" ]
