FROM {{ "bookworm" | image_tag }}

RUN {{ "nutcracker" | apt_install }} && \
    chown -R nobody /var/log/nutcracker

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/sbin/nutcracker", "--verbose=4", "--mbuf-size=65536"]
