FROM {{ registry }}/golang1.17 as build

ENV SOURCE_VERSION=v0.1.0
ENV SOURCE_REPO=https://gerrit.wikimedia.org/r/operations/software/cfssl-issuer.git
ENV CGO_ENABLED=0 GOOS=linux

RUN git clone $SOURCE_REPO && \
    cd cfssl-issuer && \
    git checkout $SOURCE_VERSION && \
    make

FROM {{ seed_image }}

COPY --from=build /go/cfss-issuer/bin/manager /usr/bin/
RUN {{ "wmf-certificates" | apt_install }}

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/manager"]
