FROM {{ "trixie" | image_tag }}

RUN echo "deb http://apt.wikimedia.org/wikimedia trixie-wikimedia thirdparty/node24" > /etc/apt/sources.list.d/nodejs.list && {{ "nodejs wmf-certificates" | apt_install }}
