FROM {{ seed_image }}

ADD envoy-future.list /etc/apt/sources.list.d/envoy-future.list

RUN {{ "envoyproxy gettext-base" | apt_install }} && \
    chown -R nobody:nogroup /etc/envoy /var/log/envoy

COPY entrypoint.sh /bin/entrypoint.sh

USER {{ "nobody" | uid }}
COPY envoy-basic-config.yaml /etc/envoy/envoy.yaml.tpl

CMD ["/bin/entrypoint.sh"]
