FROM docker-registry.wikimedia.org/wikimedia-buster

ADD envoy-future.list /etc/apt/sources.list.d/envoy-future.list

RUN {{ "envoyproxy gettext-base" | apt_install }} && \
    chown -R envoy:envoy /etc/envoy

COPY entrypoint.sh /bin/entrypoint.sh

USER envoy
COPY envoy-basic-config.yaml /etc/envoy/envoy.yaml.tpl

CMD ["/bin/entrypoint.sh"]
