FROM {{ "bookworm" | image_tag }}

ADD envoy-future.list /etc/apt/sources.list.d/envoy-future.list

RUN {{ "envoyproxy gettext-base wmf-certificates" | apt_install }} && \
    mkdir -p /var/run/envoy && \
    chown -R nobody:nogroup /etc/envoy /var/log/envoy /var/run/envoy

COPY entrypoint.sh /bin/entrypoint.sh
COPY drain-envoy.sh /bin/drain-envoy.sh

USER {{ "nobody" | uid }}
COPY envoy-basic-config.yaml /etc/envoy/envoy.yaml.tpl

ENTRYPOINT ["/bin/entrypoint.sh"]
