FROM {{ "buster" | image_tag }}

# python3-setuptools is needed to make this base image work with Blubber's
# 'python' configuration which invokes `python3 -m easy_install pip`.
RUN {{ "python3 python3-setuptools" | apt_install }}
