FROM {{ "knative-build" | image_tag }} as build

FROM {{ seed_image }}

USER root
COPY --from=build --chown=root /go/github.com/knative/serving/cmd/domain-mapping-webhook/domain-mapping-webhook /usr/bin/domain-mapping-webhook

USER {{ "nobody" | uid }}

ENTRYPOINT ["/usr/bin/domain-mapping-webhook"]
