FROM {{ "build" | image_tag }} as build

FROM {{ registry }}/bookworm:latest

USER root
COPY --from=build --chown=root /go/github.com/cert-manager/cert-manager/_bin/server/startupapicheck-linux-amd64 /usr/bin/startupapicheck

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/startupapicheck"]
