FROM {{ 'spark-build' | image_tag }} as build
FROM {{ 'spark' | image_tag }}

COPY --from=build --chown=root:root /usr/bin/spark-operator /usr/bin/spark-operator
COPY --from=build --chown=root:root /usr/bin/entrypoint.sh /usr/bin/entrypoint.sh

ENTRYPOINT /usr/bin/entrypoint.sh

USER {{ "nobody" | uid }}
