FROM {{ "build" | image_tag }} as build

FROM {{ "buster" | image_tag }}

USER root

RUN {{ "istio" | add_user }}

COPY --from=build --chown=root /go/github.com/istio/istio/out/linux_amd64/operator /usr/bin/operator

USER {{ "istio" | uid }}

ENTRYPOINT ["/usr/bin/operator"]
