FROM {{ "golang1.15" | image_tag }} as build
ENV SOURCE_REPO=https://github.com/olivierbeytrison/php-fpm-exporter

USER nobody
RUN git clone $SOURCE_REPO && \
    cd php-fpm-exporter && \
    ./script/build

FROM {{ registry }}/wikimedia-buster:latest

COPY --from=build /go/php-fpm-exporter/php-fpm-exporter.linux.amd64 /usr/bin/prometheus-php-fpm-exporter

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/prometheus-php-fpm-exporter"]
CMD ["--endpoint", "http://127.0.0.1:9181/fpm-status"]
