FROM {{ "knative-build" | image_tag }} as build

FROM {{ "bookworm" | image_tag }}

USER root
COPY --from=build --chown=root /go/github.com/knative/serving/cmd/webhook/webhook /usr/bin/webhook

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/webhook"]
