FROM {{ 'golang1.19' | image_tag }} as build

ENV SOURCE_VERSION=v2.10.0
ENV SOURCE_REPO=https://github.com/kubernetes/kube-state-metrics.git

RUN git clone $SOURCE_REPO && \
    cd kube-state-metrics && \
    git checkout $SOURCE_VERSION && \
    make build-local

FROM {{ "bookworm" | image_tag }}

COPY --from=build /go/kube-state-metrics/kube-state-metrics /usr/bin/

USER {{ "nobody" | uid }}
ENTRYPOINT ["/usr/bin/kube-state-metrics", "--port=8080", "--telemetry-port=8081"]