FROM {{ registry }}/bookworm:latest

# We declare each php_ini variable we want to be able to modify
# Note: error_reporting is using the numeric value for
# E_ALL & ~E_DEPRECATED & ~E_STRICT because symbols won't
# be expanded when interpolating env variables.
ENV PHP__date__timezone=UTC \
    PHP__default_socket_timeout=60 \
    PHP__display_errors=stderr \
    PHP__error_log= \
    PHP__error_reporting=22527 \
    PHP__include_path=".:/usr/share/php" \
    PHP__log_errors=On \
    PHP__max_execution_time=180 \
    PHP__memory_limit=200M \
    PHP__mysql__connect_timeout=3 \
    PHP__pcre__backtrack_limit=50000 \
    PHP__session__save_path=/tmp \
    ENTRY_POINT_SCRIPT=/bin/entrypoint.php

# Install all the php packages we need, and configure them.
{% set packages|replace('\n', ' ') -%}
ca-certificates
php8.5-cli
php8.5-bcmath
php8.5-bz2
php8.5-curl
php8.5-dba
php8.5-gd
php8.5-gmp
php8.5-intl
php8.5-mbstring
php8.5-mysql
php8.5-xml
php8.5-excimer
php8.5-apcu
php8.5-igbinary
php8.5-memcached
php8.5-msgpack
php8.5-redis
php8.5-uuid
{%- endset -%}
RUN echo 'deb http://apt.wikimedia.org/wikimedia bookworm-wikimedia component/php85' > /etc/apt/sources.list.d/php85.list &&\
    {{ packages | apt_install }} && \
    echo 'memcached.store_retry_count=0' >> /etc/php/8.5/mods-available/memcached.ini && \
    echo 'memcached.serializer=php' >> /etc/php/8.5/mods-available/memcached.ini && \
    sed -i"" s/compact_strings=On/compact_strings=Off/ /etc/php/8.5/mods-available/igbinary.ini && \
    echo 'mysqli.allow_local_infile=Off' >> /etc/php/8.5/mods-available/mysqli.ini && \
    echo '<?php echo "hello, world\n"; ?>' > /bin/entrypoint.php
COPY php.ini /etc/php/8.5/cli/php.ini

USER {{ "www-data" | uid }}

CMD ["/bin/bash", "-c", "/usr/bin/php8.5 ${ENTRY_POINT_SCRIPT}"]
