# Download pip wheel
#
# Debian Bullseye no longer provides any Python 2 modules, we thus install pip
# from PyPI. pip 20.3.4 is the latest version still supporting Python 2.7.
#
# The wheel serves two purposes:
#  - It is used to bootstrap the system-wide pip for python2
#  - It replaces Debian's /usr/share/python-wheels pip wheel, which virtualenv
#    uses to seed new virtual environments. The Debian wheel from
#    python-pip-whl 20.3.4-4+deb11u2 (DLA-4348-1, 2025-10-26) backported fixes
#    for CVE-2023-5752 and CVE-2025-8869 using Python-3-only syntax (f-string,
#    function annotations, str.split(maxsplit=)), so pip in any Python 2
#    virtualenv seeded from it fails with SyntaxError on `pip install`.
#
# Using the upstream wheel reintroduces those two vulnerabilities in workflows
# using this image: CVE-2023-5752 (option injection when installing from
# hg+... URLs, CVSS 3.3) and CVE-2025-8869 (symlink traversal when extracting
# a malicious sdist tarball). No pip release fixes them while retaining
# Python 2 support, so this is the tradeoff for having a functional pip;
# workflows should avoid installing from Mercurial URLs or untrusted sdists.
#
FROM {{ registry }}/bullseye:latest AS downloader

RUN apt-get update && apt-get -y install ca-certificates curl
RUN mkdir -p /downloads \
    && cd /downloads \
    && curl --no-progress-meter -O https://files.pythonhosted.org/packages/27/79/8a850fe3496446ff0d584327ae44e7500daf6764ca1a382d2d02789accf7/pip-20.3.4-py2.py3-none-any.whl \
    && echo '217ae5161a0e08c0fb873858806e3478c9775caffce5168b50ec885e358c199d pip-20.3.4-py2.py3-none-any.whl' | sha256sum --check

# The actual image
FROM {{ registry }}/bullseye:latest

ENV PYTHON_SUFFIX=2

RUN {{ "python2 python2-dev python-setuptools git lsb-release make virtualenv" | apt_install }}

# Overwrite Debian's broken python-pip-whl (installed as a dependency of virtualenv above).
COPY --from=downloader /downloads/pip-20.3.4-py2.py3-none-any.whl /usr/share/python-wheels/

# Bootstrap the "system" pip for python2 from the upstream wheel,
# then verify that a virtualenv seeded from /usr/share/python-wheels
# has a working pip (T432636).
RUN python2.7 /usr/share/python-wheels/pip-20.3.4-py2.py3-none-any.whl/pip install \
        --no-index /usr/share/python-wheels/pip-20.3.4-py2.py3-none-any.whl \
    && python2 -m pip --version \
    && python2 -m pip wheel --no-deps --wheel-dir /tmp/smoke-wheels wheel \
    && virtualenv --python python2.7 /tmp/smoke-venv \
    && /tmp/smoke-venv/bin/pip install --isolated --no-index --no-deps /tmp/smoke-wheels/*.whl \
    && rm -fR /tmp/smoke-wheels /tmp/smoke-venv

RUN mkdir /wheels && python2 -m pip install wheel

COPY run.sh /bin/run.sh

# These volumes are respectively where the wheels will be built, and where the code for the application resides
VOLUME ["/wheels", "/deploy"]

USER nobody

WORKDIR /deploy

CMD ["/bin/run.sh"]
