FROM {{ seed_image }}
RUN {{ "prometheus-statsd-exporter" | apt_install }} \
   && rm -rf /usr/share/gocode/src/github.com/prometheus


ENTRYPOINT ["/usr/bin/prometheus-statsd-exporter"]
CMD ["--statsd.mapping-config=/etc/monitoring/prometheus-statsd.conf"]
