FROM docker-registry.wikimedia.org/istio/build:latest as build

FROM {{ seed_image }}

USER root
RUN {{ "istio" | add_user }}

COPY --from=build --chown=root /go/github.com/istio/istio/out/linux_amd64/pilot-discovery /usr/bin/pilot-discovery

USER {{ "istio" | uid }}
ENTRYPOINT ["/usr/bin/pilot-discovery"]
