FROM {{ "trixie" | image_tag }}
# openjdk-25-jre-headless:amd64 (25.0.3+9-2~deb13u1) fails post-inst like:
# update-alternatives: error: error creating symbolic link '/usr/share/man/man1/java.1.gz.dpkg-tmp': No such file or directory
# Just create the directory to make it happy.
RUN mkdir -p /usr/share/man/man1/ && \
    {{ "openjdk-25-jre-headless" | apt_install }}
