FROM {{ registry }}/{{ seed_image }}:latest
LABEL Description="Fluent-bit image to run as a sidecar container" \
      maintainer="joe@wikimedia.org"

{{ "td-agent-bit" | apt_install }}


COPY fluent-bit.conf /etc/td-agent-bit/td-agent-bit.conf

# Entry point
CMD ["/opt/td-agent-bit/bin/td-agent-bit", "-c", "/etc/td-agent-bit/td-agent-bit.conf"]
