FROM {{ registry }}/wikimedia-jessie:latest

{{ "statsd-proxy gettext-base" | apt_install }}

COPY statsd-proxy.cfg /etc/statsd-proxy.cfg.tpl
COPY entrypoint.sh /bin/entrypoint

ENV STATSD_HOST localhost
ENV STATSD_PORT 8126


ENTRYPOINT ["/bin/entrypoint"]
