FROM {{ registry }}/trixie:latest

RUN {{ "python3 python3-dev python3-pip python3-setuptools python3-venv python3-wheel git lsb-release make virtualenv" | apt_install }} \
    && mkdir /wheels

COPY run.sh /bin/run.sh

# These volumes are respectively where the wheels will be built, and where the code for the application resides
VOLUME ["/wheels", "/deploy"]

USER nobody

WORKDIR /deploy

CMD ["/bin/run.sh"]
