FROM docker-registry.wikimedia.org/cert-manager-build:latest as build

FROM {{ seed_image }}

USER root
COPY --from=build --chown=root /go/github.com/jetstack/cert-manager/cmd/webhook/webhook /usr/bin/webhook

USER nobody
ENTRYPOINT ["/usr/bin/webhook"]
